//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Orders = new HashSet<Orders>();
            this.Orders1 = new HashSet<Orders>();
        }
    
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientINN { get; set; }
        public int ClientAddressKey { get; set; }
        public string ClientPhone { get; set; }
        public bool ClientSalesmanBool { get; set; }
        public bool ClientBuyerBool { get; set; }
    
        public virtual ClientAddresses ClientAddresses { get; set; }
        public virtual ClientAddresses ClientAddresses1 { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Orders> Orders1 { get; set; }
    }
}
