//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAddresses
    {
        public ClientAddresses()
        {
            this.Clients = new HashSet<Clients>();
            this.Clients1 = new HashSet<Clients>();
        }
    
        public int ClientAddressID { get; set; }
        public string ClientAddressCity { get; set; }
        public string ClientAddressStreet { get; set; }
        public string ClientAddressBuilding { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Clients> Clients1 { get; set; }
    }
}
