//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilkBaseEntities : DbContext
    {
        public MilkBaseEntities()
            : base("name=MilkBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClientAddresses> ClientAddresses { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Manufacturers> Manufacturers { get; set; }
        public DbSet<Materials> Materials { get; set; }
        public DbSet<MeasureUnits> MeasureUnits { get; set; }
        public DbSet<OrderExecutors> OrderExecutors { get; set; }
        public DbSet<OrderItems> OrderItems { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<ProductionMaterials> ProductionMaterials { get; set; }
        public DbSet<ProductionProducts> ProductionProducts { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<ProductSpecifications> ProductSpecifications { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
