//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturers
    {
        public Manufacturers()
        {
            this.ProductSpecifications = new HashSet<ProductSpecifications>();
            this.ProductSpecifications1 = new HashSet<ProductSpecifications>();
        }
    
        public int ManufacturerID { get; set; }
        public string ManufacturerName { get; set; }
    
        public virtual ICollection<ProductSpecifications> ProductSpecifications { get; set; }
        public virtual ICollection<ProductSpecifications> ProductSpecifications1 { get; set; }
    }
}
