//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.ProductionMaterials = new HashSet<ProductionMaterials>();
            this.ProductionMaterials1 = new HashSet<ProductionMaterials>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public decimal Price { get; set; }
        public int MeasureUnitKey { get; set; }
    
        public virtual MeasureUnits MeasureUnits { get; set; }
        public virtual MeasureUnits MeasureUnits1 { get; set; }
        public virtual ICollection<ProductionMaterials> ProductionMaterials { get; set; }
        public virtual ICollection<ProductionMaterials> ProductionMaterials1 { get; set; }
    }
}
