//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasureUnits
    {
        public MeasureUnits()
        {
            this.Materials = new HashSet<Materials>();
            this.Materials1 = new HashSet<Materials>();
            this.Products = new HashSet<Products>();
            this.Products1 = new HashSet<Products>();
        }
    
        public int MeasureUnitID { get; set; }
        public string MeasureUnitName { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
        public virtual ICollection<Materials> Materials1 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Products> Products1 { get; set; }
    }
}
