//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderExecutors
    {
        public OrderExecutors()
        {
            this.Orders = new HashSet<Orders>();
            this.Orders1 = new HashSet<Orders>();
        }
    
        public int OrderExecutorID { get; set; }
        public string OrderExecutorName { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Orders> Orders1 { get; set; }
    }
}
