//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int OrderExecutorKey { get; set; }
        public int ClientKey { get; set; }
        public int OrderItemKey { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Status { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Clients Clients1 { get; set; }
        public virtual OrderExecutors OrderExecutors { get; set; }
        public virtual OrderExecutors OrderExecutors1 { get; set; }
        public virtual OrderItems OrderItems { get; set; }
        public virtual OrderItems OrderItems1 { get; set; }
    }
}
