//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public OrderItems()
        {
            this.Orders = new HashSet<Orders>();
            this.Orders1 = new HashSet<Orders>();
        }
    
        public int OrderItemID { get; set; }
        public int ProductKey { get; set; }
        public byte ProductQuantity { get; set; }
        public decimal Weight { get; set; }
        public decimal Summ { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Products Products1 { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Orders> Orders1 { get; set; }
    }
}
