//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionMaterials
    {
        public ProductionMaterials()
        {
            this.ProductionProducts = new HashSet<ProductionProducts>();
            this.ProductionProducts1 = new HashSet<ProductionProducts>();
        }
    
        public int ProductionMaterialID { get; set; }
        public int MaterialKey { get; set; }
        public byte MaterialQuantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Materials Materials1 { get; set; }
        public virtual ICollection<ProductionProducts> ProductionProducts { get; set; }
        public virtual ICollection<ProductionProducts> ProductionProducts1 { get; set; }
    }
}
