//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecifications
    {
        public int ProductSpecificationID { get; set; }
        public int ProductionProductKey { get; set; }
        public int ManufacturerKey { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Manufacturers Manufacturers1 { get; set; }
        public virtual Products Products { get; set; }
        public virtual Products Products1 { get; set; }
    }
}
