//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.OrderItems1 = new HashSet<OrderItems>();
            this.ProductionProducts = new HashSet<ProductionProducts>();
            this.ProductionProducts1 = new HashSet<ProductionProducts>();
            this.ProductSpecifications = new HashSet<ProductSpecifications>();
            this.ProductSpecifications1 = new HashSet<ProductSpecifications>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public byte ProductFatPercent { get; set; }
        public decimal Weight { get; set; }
        public int MeasureUnitKey { get; set; }
        public decimal Price { get; set; }
    
        public virtual MeasureUnits MeasureUnits { get; set; }
        public virtual MeasureUnits MeasureUnits1 { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ICollection<OrderItems> OrderItems1 { get; set; }
        public virtual ICollection<ProductionProducts> ProductionProducts { get; set; }
        public virtual ICollection<ProductionProducts> ProductionProducts1 { get; set; }
        public virtual ICollection<ProductSpecifications> ProductSpecifications { get; set; }
        public virtual ICollection<ProductSpecifications> ProductSpecifications1 { get; set; }
    }
}
