//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionProducts
    {
        public int ProductionID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int ProductKey { get; set; }
        public decimal Weight { get; set; }
        public int ProductionMaterialKey { get; set; }
    
        public virtual ProductionMaterials ProductionMaterials { get; set; }
        public virtual ProductionMaterials ProductionMaterials1 { get; set; }
        public virtual Products Products { get; set; }
        public virtual Products Products1 { get; set; }
    }
}
