//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkBase_9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserSecondName { get; set; }
        public string UserFirstName { get; set; }
        public string UserPatronymic { get; set; }
        public int UserRoleKey { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
        public bool IsBlocked { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Roles Roles1 { get; set; }
    }
}
